### ISSUE TITLE
[META] Build out survey models and views.

### ISSUE THREAD

**Issue by a-pasquale** [hackforwesternmass/verite#4]
~~Determine survey tool and API endpoints~~

It sounds like @pdw207 has determined that with the specificity of the data returns they want to do across surveys the survey will be hosted in the Laravel App. 

We'll need:

- [ ] Data Models (for each survey?), but let's start by getting an example survey and build out the models and views from there for that one.

  - [ ] @pdw207 will get an example survey from Verite that they made on Qualtrix

  - [ ] Once we have the survey @serundeputy and Jay Barnes can work to build out the Models and views for it.
    * Group surveys
      * meta data on # of Male and # Female survey participants
    * Individual surveys

- [ ] An admin interface/UI to add additional surveys.

- [ ] A dashboard view of surveys that can list completed surveys with drill down links into the details

- [ ] Some search and reporting functionality so Verite staff can query results and generate reports and charts (export them?)

**Comment by a-pasquale** [comment]
Here's a link to survey monkey api docs: https://developer.surveymonkey.com/api/v3/

**Comment by jrabbit** [comment]
Yeah is there an abstraction library that we could work with to make their choice "cheaper"? I don't know much about surveys

**Comment by serundeputy** [comment]
PR: https://github.com/hackforwesternmass/verite/pull/7

PR adds the Models, Controllers and Views for the survey creating it is adapted from https://blog.khophi.co/10-days-laravel-5-laravel-survey-app/ and is on the `surveys` branch.

There is still work to be done in connecting all the CRUD operations correctly as many of the routes in `web.php` are blowing up due to the blade files calling things from the `laravel-survey-app` from the tutorial that don't exist in the `verite` app.  Need to go through the routes and fix errors:

- [x] Route::get('/survey/new', 'SurveyController@newSurvey')->name('new.survey');
- [x] Route::get('/survey/{survey}', 'SurveyController@detailSurvey')->name('detail.survey');
- [x] Route::get('/survey/view/{survey}', 'SurveyController@viewSurvey')->name('view.survey');
- [x] Route::get('/survey/answers/{survey}', 'SurveyController@viewSurveyAnswers')->name('view.survey.answers');
- [x] Route::get('/survey/{survey}/delete', 'SurveyController@deleteSurvey')->name('delete.survey');

- [x] Route::get('/survey/{survey}/edit', 'SurveyController@edit')->name('edit.survey');
- [ ] Route::patch('/survey/{survey}/update', 'SurveyController@update')->name('update.survey');

- [ ] Route::post('/survey/view/{survey}/completed', 'AnswerController@store')->name('complete.survey');
- [ ] Route::post('/survey/create', 'SurveyController@create')->name('create.survey');

// Questions related
- [ ] Route::post('/survey/{survey}/questions', 'QuestionController@store')->name('store.question');

- [x] Route::get('/question/{question}/edit', 'QuestionController@edit')->name('edit.question');
- [ ] Route::patch('/question/{question}/update', 'QuestionController@update')->name('update.question');

**Comment by a-pasquale** [comment]
Most of the errors in these routes are fixed in commits 9dc185a, 18ffa54, a2b3527, and 0f9d724.
